config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  resources :articles, only: [:show, :new]
  resources :users, only: [:show, :new]
  resources :sessions, only: :new
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/new.html.erb
<p>これが「articles#new」ページだよ</p>

app/views/articles/show.html.erb
<p>これが「articles#show」ページだよ</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>イカボー</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h2>イカボー</h2>
<p>こんにちは、このサイトはとても素晴らしいサイトです</p>

<p><%= link_to 'Articles#Show', article_path(1) %></p>
<p><%= link_to 'Articles#New', new_article_path %></p>
<p><%= link_to 'Users#Show', user_path(1) %></p>
<p><%= link_to 'Users#New', new_user_path %></p>
<p><%= link_to 'Sessions#New', new_session_path %></p>

app/views/users/new.html.erb
<p>これが「users#new」ページだよ</p>
<p>わかってくれ</p>

app/views/users/show.html.erb
<p>これが「users#show」ページだよ</p>
<p>わかってくれ</p>